services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always
    networks:
      - lsst

  broker1:
    image: confluentinc/cp-kafka:latest
    container_name: broker1
    hostname: broker1
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper1
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper1:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXT:PLAINTEXT,INT:PLAINTEXT
      KAFKA_LISTENERS: EXT://broker1:9092,INT://broker1:29092
      KAFKA_ADVERTISED_LISTENERS: EXT://broker1:9092,INT://broker1:29092
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_INTER_BROKER_LISTENER_NAME: INT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - lsst

  mirrormaker2:
    image: confluentinc/cp-kafka-connect:latest
    container_name: mirrormaker2
    healthcheck:
      test: [ "NONE" ]
    depends_on:
      - zookeeper1
      - broker1
    restart: always
    command:
      - /bin/connect-mirror-maker
      - /etc/kafka-connect/mm2.properties
    volumes:
      - ./mm2.properties:/etc/kafka-connect/mm2.properties:ro
      - ./kafka-log4j.properties:/etc/kafka-connect/kafka-log4j.properties:ro
    environment:
      KAFKA_LOG4J_OPTS: -Dlog4j.configuration=file:/etc/kafka-connect/kafka-log4j.properties
    networks:
      - lsst

  ingestd_dc2:
    image: ghcr.io/lsst-dm/ctrl_ingestd:1.5
    container_name: ingestd_dc2
    depends_on:
      - broker1
    restart: always
    environment:
      CTRL_INGESTD_CONFIG: /tmp/ingestd-configs/dc2.yaml
      LSST_DB_AUTH: /tmp/db-auth.yaml
      DAF_BUTLER_REPOSITORY_INDEX: /etc/butler-repos-index.yaml
    volumes:
      - ./butler-repos/butler-repos-index.yaml:/etc/butler-repos-index.yaml:ro
      - ./ingestd-configs/hsc_pdr2_multisite.yaml:/tmp/ingestd-configs/hsc_pdr2_multisite.yaml:ro
      - ./ingestd-configs/ccms1.yaml:/tmp/ingestd-configs/ccms1.yaml:ro
      - ./db-auth.yaml:/tmp/db-auth.yaml:ro
      - ./butler-repos/panda-test-med-1-lancs/butler.yaml:/etc/panda-test-med-1-lancs/butler.yaml
      - ./butler-repos/hsc-pdr2-multisite/butler.yaml:/etc/hsc-pdr2-multisite/butler.yaml
      - ./butler-repos/ccms1/butler.yaml:/etc/ccms1/butler.yaml
      - ./butler-repos/dc2/butler.yaml:/etc/panda-test-med-1/butler.yaml
      - ./ingestd-configs/dc2.yaml:/tmp/ingestd-configs/dc2.yaml
    networks:
      - lsst

  ingestd_ccms1:
    image: ghcr.io/lsst-dm/ctrl_ingestd:1.5
    container_name: ingestd_ccms1
    depends_on:
      - broker1
    restart: always
    environment:
      CTRL_INGESTD_CONFIG: /tmp/ingestd-configs/ccms1.yaml
      LSST_DB_AUTH: /tmp/db-auth.yaml
      DAF_BUTLER_REPOSITORY_INDEX: /etc/butler-repos-index.yaml
    volumes:
      - ./butler-repos/butler-repos-index.yaml:/etc/butler-repos-index.yaml:ro
      - ./ingestd-configs/hsc_pdr2_multisite.yaml:/tmp/ingestd-configs/hsc_pdr2_multisite.yaml:ro
      - ./ingestd-configs/ccms1.yaml:/tmp/ingestd-configs/ccms1.yaml:ro
      - ./db-auth.yaml:/tmp/db-auth.yaml:ro
      - ./butler-repos/panda-test-med-1-lancs/butler.yaml:/etc/panda-test-med-1-lancs/butler.yaml
      - ./butler-repos/hsc-pdr2-multisite/butler.yaml:/etc/hsc-pdr2-multisite/butler.yaml
      - ./butler-repos/ccms1/butler.yaml:/etc/ccms1/butler.yaml
      - ./butler-repos/dc2/butler.yaml:/etc/panda-test-med-1/butler.yaml
      - ./ingestd-configs/dc2.yaml:/tmp/ingestd-configs/dc2.yaml
    networks:
      - lsst

  ingestd_hsc_pdr2_multisite:
    image: ghcr.io/lsst-dm/ctrl_ingestd:1.5
    container_name: hsc_pdr2_multisite
    depends_on:
      - broker1
    restart: always
    environment:
      CTRL_INGESTD_CONFIG: /tmp/ingestd-configs/hsc_pdr2_multisite.yaml
      LSST_DB_AUTH: /tmp/db-auth.yaml
      DAF_BUTLER_REPOSITORY_INDEX: /etc/butler-repos-index.yaml
    volumes:
      - ./butler-repos/butler-repos-index.yaml:/etc/butler-repos-index.yaml:ro
      - ./ingestd-configs/hsc_pdr2_multisite.yaml:/tmp/ingestd-configs/hsc_pdr2_multisite.yaml:ro
      - ./ingestd-configs/ccms1.yaml:/tmp/ingestd-configs/ccms1.yaml:ro
      - ./db-auth.yaml:/tmp/db-auth.yaml:ro
      - ./butler-repos/panda-test-med-1-lancs/butler.yaml:/etc/panda-test-med-1-lancs/butler.yaml
      - ./butler-repos/hsc-pdr2-multisite/butler.yaml:/etc/hsc-pdr2-multisite/butler.yaml
      - ./butler-repos/ccms1/butler.yaml:/etc/ccms1/butler.yaml
      - ./butler-repos/dc2/butler.yaml:/etc/panda-test-med-1/butler.yaml
      - ./ingestd-configs/dc2.yaml:/tmp/ingestd-configs/dc2.yaml
    networks:
      - lsst

  ## Relevant links for the following container which is used for
  ## exporting performance metrics from Kafka to Prometheus
  # https://prometheus.github.io/jmx_exporter/
  # https://github.com/danielqsj/kafka_exporter
  # https://www.redpanda.com/guides/kafka-performance-kafka-monitoring

  kafka-exporter:
    image: danielqsj/kafka-exporter
    container_name: kafka-exporter
    command: ["--kafka.server=broker1:9092"]
    ports:
      - 9308:9308
    networks:
      - lsst

  # rest-proxy:
  #   image: confluentinc/cp-kafka-rest:latest
  #   ports:
  #     - "8082:8082"
  #   depends_on:
  #     - zookeeper1
  #     - broker1
  #   hostname: rest-proxy
  #   container_name: rest-proxy
  #   environment:
  #     KAFKA_REST_HOST_NAME: rest-proxy
  #     KAFKA_REST_BOOTSTRAP_SERVERS: broker1:9092
  #     KAFKA_REST_LISTENERS: http://127.0.0.1:8082
  #   networks:
  #     - lsst
  
networks:
  lsst:
    driver: bridge
