services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always

  broker1:
    image: confluentinc/cp-kafka:latest
    container_name: broker1
    hostname: broker1
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper1
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper1:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXT:PLAINTEXT,INT:PLAINTEXT
      KAFKA_LISTENERS: EXT://0.0.0.0:9092,INT://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: EXT://130.246.80.239:9092,INT://broker1:29092
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_INTER_BROKER_LISTENER_NAME: INT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mirrormaker2:
    image: confluentinc/cp-kafka-connect:latest
    container_name: mirrormaker2
    healthcheck:
      test: [ "NONE" ]
    depends_on:
      - zookeeper1
      - broker1
    restart: always
    command:
      - /bin/connect-mirror-maker
      - /etc/kafka-connect/mm2.properties
    volumes:
      - ./mm2.properties:/etc/kafka-connect/mm2.properties:ro
      - ./kafka-log4j.properties:/etc/kafka-connect/kafka-log4j.properties:ro

    environment:
      KAFKA_LOG4J_OPTS: -Dlog4j.configuration=file:/etc/kafka-connect/kafka-log4j.properties

  ingestd:
    image: ghcr.io/lsst-dm/ctrl_ingestd:1.2
    container_name: ingestd
    depends_on:
      - broker1
    restart: always
    environment:
      CTRL_INGESTD_CONFIG: /etc/ingestd.yaml
      LSST_DB_AUTH: /etc/db-auth.yaml
      DAF_BUTLER_REPOSITORY_INDEX: /etc/butler-repos-index.yaml
    volumes:
      - ./butler-repos-index.yaml:/etc/butler-repos-index.yaml:ro
      - ./ingestd.yaml:/etc/ingestd.yaml:ro
      - /etc/db-auth.yaml:/etc/db-auth.yaml:ro

  rest-proxy:
    image: confluentinc/cp-kafka-rest:latest
    ports:
      - "8082:8082"
    depends_on:
      - zookeeper1
      - broker1
    hostname: rest-proxy
    container_name: rest-proxy
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: 'broker1:29092'
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"