{
 "title": "LSST DRP Kafka Overview",
 "description": "Kafka resource usage and throughput",
 "tags": [ "Kafka" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_topic_partitions{topic=~\".+\", topic!~\"__consumer_offsets|mm2-configs.source.internal|mm2-offsets.source.internal|mm2-status.source.internal\"}, topic)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Necessary health checks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of active controllers",
   "type": "gauge",
   "description": "### Should be 1 for proper functioning\n\nThe active controller count metric indicates whether the broker is currently the controller for the cluster.\n\nThe metric will either be 0 or 1, with 1 showing that the broker is currently the controller (Since we have a single broker setup, this should always be 1).\n\n#### Possible reasons\n* At all times, only one broker should be the controller, and one broker must always be the controller in the cluster.<br><br>\n* If two brokers say that they are currently the controller, this means that you have a problem where a controller thread that should have exited has become stuck\n\n*Kafka the Definitive Guide*, Narkhede N., Shapira G., Palino T.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Under Replicated Partitions",
   "type": "gauge",
   "description": "### Should be 0 for proper functioning\n\nProvided on each broker in a cluster, gives a count of the number of partitions for which the broker is the leader replica, where the follower replicas are not caught up.\n\n#### Possible reasons\n* Steady (unchanging) value reported by many of the brokers in a cluster normally indicates that one of the brokers in the cluster is off‐line.<br><br>\n\n* If value is fluctuating, or if the number is steady but there are no brokers offline, this typically indicates a performance issue in the cluster.\n\n*Kafka the Definitive Guide*, Narkhede N., Shapira G., Palino T.",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Offline Partitions",
   "type": "gauge",
   "description": "### Should be 0 for proper functioning\n\nThis measurement is only provided by\nthe broker that is the controller for the cluster (all other brokers will report 0), and shows the number of partitions in the cluster that currently have no leader.\n\n#### Possible reasons\n* All brokers hosting replicas for this partition are down.<br><br>\n* No in-sync replica can take leadership due to message-count mismatches (with unclean leader election disabled).\n\n*Kafka the Definitive Guide*, Narkhede N., Shapira G., Palino T.",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USDF heartbeats bytes in",
   "type": "timeseries",
   "description": "The way consumers maintain membership in a consumer group and ownership of the partitions assigned to them is by sending heartbeats to a Kafka broker designated as the group coordinator.\n\nAs long as the consumer is sending heartbeats at regular intervals, it is assumed to be alive, well, and processing messages from its partitions. Heartbeats are sent when the consumer polls (i.e., retrieves records) and when it commits records it has consumed\n\n*Kafka the Definitive Guide*, Narkhede N., Shapira G., Palino T.",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "irate(kafka_server_brokertopicmetrics_bytesin_total{job=\"prometheus-jmx-exporter\", topic=\"usdf.heartbeats\"}[1m])",
     "legendFormat": "{{topic}} bytes in = "
    }
   ]
  },
  { "title": "Hardware use", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(jvm_threads_current{job=\"prometheus-jmx-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area) (jvm_memory_used_bytes{job=\"prometheus-jmx-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{job=\"prometheus-jmx-exporter\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"prometheus-jmx-exporter\"}[1m])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Disk writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_kafkaserver_linux_disk_write_bytes{job=\"prometheus-jmx-exporter\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk read bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_kafkaserver_linux_disk_read_bytes{job=\"prometheus-jmx-exporter\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Produced vs Consumed messages (should be the same)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }
  },
  {
   "title": "Messages In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(kafka_server_brokertopicmetrics_messagesin_total{job=\"prometheus-jmx-exporter\", topic=~\".+\", topic!~\"usdf.heartbeats\"}[1m])",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "irate(kafka_server_brokertopicmetrics_messagesin_total{job=\"prometheus-jmx-exporter\", topic=~\"$topic\", topic!~\"usdf.heartbeats\"}[1m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages out per topic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum without(instance) (rate(kafka_server_brokertopicmetrics_messages{job=\"kafka-deployment-health\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(kafka_server_brokertopicmetrics_bytesin_total{job=\"prometheus-jmx-exporter\", topic=~\".+\", topic!~\"usdf.heartbeats\"}[1m])",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "irate(kafka_server_brokertopicmetrics_bytesin_total{job=\"prometheus-jmx-exporter\", topic=~\"$topic\", topic!~\"usdf.heartbeats\"}[1m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(kafka_server_brokertopicmetrics_bytesout_total{job=\"prometheus-jmx-exporter\", topic=~\".+\", topic!~\"usdf.heartbeats\"}[1m])",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "irate(kafka_server_brokertopicmetrics_bytesout_total{job=\"prometheus-jmx-exporter\", topic=~\"$topic\", topic!~\"usdf.heartbeats\"}[1m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Miscellaneous", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Number of partitions",
   "type": "bargauge",
   "description": "Messages in Kafka are categorized into topics. Topics are additionally broken down into a number of *partitions*. \n\nMessages are written to partitions in an append-only and messages are time ordered within partitions (not within topics). They can also be hosted on different servers which helps in scalability.\n\n*Kafka the Definitive Guide*, Narkhede N., Shapira G., Palino T.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partitions{topic=~\"$topic\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Lag by  Consumer Group",
   "type": "timeseries",
   "description": "Consumer lag is the number of consumer offsets between the latest message produced in a partition and the last message consumed by a consumer, that is the number of messages pending to be consumed from a particular partition.\n\n#### Possible reasons\nA large consumer lag, or a quickly growing lag, indicates that the consumer is unable to read from a partition as fast as the messages are available. This can be caused by:\n* slow consumer\n* slow network, or \n* slow broker\n\n[Consumer lag - Confluent Apache Kafka Glossary](https://docs.confluent.io/cloud/current/_glossary.html#term-consumer-lag)",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "kafka_consumergroup_members", "legendFormat": "{{consumergroup}}" }
   ]
  }
 ]
}