# Mark provisioned data sources for deletion if they are no longer in a provisioning file.
# It takes no effect if data sources are already listed in the deleteDatasources section.
apiVersion: 1

prune: true

datasources:
-  name: 'test-data'
   type: 'testdata'
   access: 'proxy'
   isDefault: true
   editable: true
   org_id: 1

-  name: 'prometheus-data'
   type: 'prometheus'
   url: 'http://prometheus:9090'
   access: 'proxy'
   editable: true
   org_id: 1
   version: 1