# The configuration file to define

receivers:
  # The jmx receiver in the community contributions OpenTelemetry Collector
  # Link to the receiver:
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/jmxreceiver

  jmx:
    jar_path: /opt/opentelemetry-jmx-metrics.jar
    endpoint: service:jmx:rmi:///jndi/rmi://broker1:9101/jmxrmi
    target_system: "jvm,kafka" # Important: These must have no whitespace between them
    collection_interval: 10s

  # The kafka metrics receiver in the community contributions OpenTelemetry Collector
  # Link to the receiver:
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kafkametricsreceiver

  kafkametrics:
    brokers: ["broker1:9092"]
    # Metric scrapers to enable
    scrapers:
      - brokers
      - topics
      - consumers

processors:
  batch:
    timeout: 10s

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

  prometheus:
    # Expose on port 8889 for Prometheus scraping
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    metrics:
      receivers: [jmx]
      processors: [batch]
      exporters: [prometheus]