apiVersion: v1
kind: ConfigMap
metadata:
  name: ingestd-configs
  namespace: lsst-drp
data:
  dc2.yaml: |
    brokers: lsst-kafka-cluster-kafka-bootstrap:9092
    group_id: "ral_ingestd"
    num_messages: 50
    butler:
      repo: panda-test-med-1
    topics:
      usdf.RAL_BUTLER_DISK-dc2:
        rucio_prefix: davs://xrootd.echo.stfc.ac.uk:1094/lsst:datadisk/butler/
        fs_prefix: https://webdav.echo.stfc.ac.uk:1094/lsst:datadisk/butler/job_outputs/
      usdf.RAL_RAW_DISK-dc2:
        rucio_prefix: https://webdav.echo.stfc.ac.uk:1094/lsst:datadisk/raw/
        fs_prefix: https://webdav.echo.stfc.ac.uk:1094/lsst:datadisk/raw/job_outputs/
  ccms1.yaml: |
    brokers: lsst-kafka-cluster-kafka-bootstrap:9092
    group_id: "ral_ingestd"
    num_messages: 50
    butler:
      repo: ccms1
    topics:
      usdf.RAL_BUTLER_DISK-ccms1:
        rucio_prefix: davs://xrootd.echo.stfc.ac.uk:1094/lsst:datadisk/butler/
        fs_prefix: https://webdav.echo.stfc.ac.uk:1094/lsst:datadisk/butler/job_outputs/
      usdf.RAL_RAW_DISK-ccms1:
        rucio_prefix: https://webdav.echo.stfc.ac.uk:1094/lsst:datadisk/raw/
        fs_prefix: https://webdav.echo.stfc.ac.uk:1094/lsst:datadisk/raw/job_outputs/
  hsc_pdr2_multisite.yaml: |
    brokers: lsst-kafka-cluster-kafka-bootstrap:9092
    group_id: "ral_ingestd"
    num_messages: 50
    butler:
      repo: hsc_pdr2_multisite
    topics:
      usdf.RAL_BUTLER_DISK-hsc_pdr2_multisite:
        rucio_prefix: davs://xrootd.echo.stfc.ac.uk:1094/lsst:datadisk/butler/
        fs_prefix: https://webdav.echo.stfc.ac.uk:1094/lsst:datadisk/butler/job_outputs/
      usdf.RAL_RAW_DISK-hsc_pdr2_multisite:
        rucio_prefix: https://webdav.echo.stfc.ac.uk:1094/lsst:datadisk/raw/
        fs_prefix: https://webdav.echo.stfc.ac.uk:1094/lsst:datadisk/raw/job_outputs/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: butler-repos-index
  namespace: lsst-drp
data:
  butler-repos-index.yaml: |
    panda-test-med-1: /etc/panda-test-med-1-lancs/butler.yaml
    hsc_pdr2_multisite: /etc/hsc-pdr2-multisite/butler.yaml
    dc2: /etc/panda-test-med-1-lancs/butler.yaml
    ccms1: /etc/ccms1/butler.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: butler-repos
  namespace: lsst-drp
data:
  panda-test-med-1-lancs-butler.yaml: |
    datastore:
      cls: lsst.daf.butler.datastores.fileDatastore.FileDatastore
      records:
        table: file_datastore_records
      root: <butlerRoot>
    registry:
      db: postgresql://dbspgha03.fds.rl.ac.uk:5432/ral_butler
      managers:
        attributes: lsst.daf.butler.registry.attributes.DefaultButlerAttributeManager
        collections: lsst.daf.butler.registry.collections.synthIntKey.SynthIntKeyCollectionManager
        datasets: lsst.daf.butler.registry.datasets.byDimensions.ByDimensionsDatasetRecordStorageManagerUUID
        datastores: lsst.daf.butler.registry.bridge.monolithic.MonolithicDatastoreRegistryBridgeManager
        dimensions: lsst.daf.butler.registry.dimensions.static.StaticDimensionRecordStorageManager
        opaque: lsst.daf.butler.registry.opaque.ByNameOpaqueTableStorageManager
      namespace: panda_test_med_1
  hsc-pdr2-multisite-butler.yaml: |
    datastore:
      name: hsc_pdr2_multisite
      cls: lsst.daf.butler.datastores.fileDatastore.FileDatastore
      records:
        table: file_datastore_records
      root: https://webdav.echo.stfc.ac.uk:1094/lsst:datadisk/butler/repos/hsc_pdr2_multisite
    registry:
      db: postgresql://dbspgha03.fds.rl.ac.uk:5432/ral_butler
      managers:
        attributes: lsst.daf.butler.registry.attributes.DefaultButlerAttributeManager
        collections: lsst.daf.butler.registry.collections.synthIntKey.SynthIntKeyCollectionManager
        datasets: lsst.daf.butler.registry.datasets.byDimensions.ByDimensionsDatasetRecordStorageManagerUUID
        datastores: lsst.daf.butler.registry.bridge.monolithic.MonolithicDatastoreRegistryBridgeManager
        dimensions: lsst.daf.butler.registry.dimensions.static.StaticDimensionRecordStorageManager
        opaque: lsst.daf.butler.registry.opaque.ByNameOpaqueTableStorageManager
      namespace: hsc_pdr2_multisite
  ccms1-butler.yaml: |
    datastore:
      cls: lsst.daf.butler.datastores.fileDatastore.FileDatastore
      records:
        table: file_datastore_records
      root: <butlerRoot>
    registry:
      db: postgresql://dbspgha03.fds.rl.ac.uk:5432/ral_butler
      managers:
        attributes: lsst.daf.butler.registry.attributes.DefaultButlerAttributeManager
        collections: lsst.daf.butler.registry.collections.synthIntKey.SynthIntKeyCollectionManager
        datasets: lsst.daf.butler.registry.datasets.byDimensions.ByDimensionsDatasetRecordStorageManagerUUID
        datastores: lsst.daf.butler.registry.bridge.monolithic.MonolithicDatastoreRegistryBridgeManager
        dimensions: lsst.daf.butler.registry.dimensions.static.StaticDimensionRecordStorageManager
        opaque: lsst.daf.butler.registry.opaque.ByNameOpaqueTableStorageManager
      namespace: ccms1
  dc2-butler.yaml: |
    datastore:
      cls: lsst.daf.butler.datastores.fileDatastore.FileDatastore
      records:
        table: file_datastore_records
      root: <butlerRoot>
    registry:
      db: postgresql://dbspgha03.fds.rl.ac.uk:5432/ral_butler
      managers:
        attributes: lsst.daf.butler.registry.attributes.DefaultButlerAttributeManager
        collections: lsst.daf.butler.registry.collections.synthIntKey.SynthIntKeyCollectionManager
        datasets: lsst.daf.butler.registry.datasets.byDimensions.ByDimensionsDatasetRecordStorageManagerUUID
        datastores: lsst.daf.butler.registry.bridge.monolithic.MonolithicDatastoreRegistryBridgeManager
        dimensions: lsst.daf.butler.registry.dimensions.static.StaticDimensionRecordStorageManager
        opaque: lsst.daf.butler.registry.opaque.ByNameOpaqueTableStorageManager
      namespace: panda_test_med_1