apiVersion: v1
kind: ServiceMonitor
metadata:
  name: kafka-metrics
  namespace: lsst-drp
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      strimzi.io/name: lsst-kafka-cluster-kafka
  endpoints:
  - port: tcp-prometheus
    interval: 30s
    path: /metrics
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: kafka-exporter-metrics
  namespace: lsst-drp
  labels:
    app: kafka-exporter
spec:
  selector:
    matchLabels:
      app: kafka-exporter-external
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: mirrormaker2-metrics
  namespace: lsst-drp
  labels:
    app: mirrormaker2
spec:
  selector:
    matchLabels:
      strimzi.io/name: mirrormaker2-connect
  endpoints:
  - port: tcp-prometheus
    interval: 30s
    path: /metrics